### ISSUE TITLE
Pa11y and Logins

### ISSUE THREAD

**Issue by qaDream77** [nature/pa11y#122]
So i opened the original ticket about authentication months ago and you suggested that running phantom code before pa11y executes would be the best solution.

I was wondering if there was any ETA on this or if i can help contribute?

Ideally all pa11y needs to do is scan the currently opened webpage
: phantomjs code beforehand

in some cases it is also useful to be able to take screenshots, so another idea might be to
: to run pa11y + Firefox as a proxy. You could navigate to the site, tell pa11y to run and it would generate the report for you. Authentication could be handled manually or via any web driver such as selenium.

In either case, we're telling pa11y to execute on the currently opened webpage. Whichever method is easier but it might be worthwhile to consider adding selenium support in a future release.

Cheers Jordan.

**Comment by rowanmanning** [comment]
Hi @qaDream77,

There's not an ETA as such but it is being worked on here: #98. You may be able to contribute but I think it's really a case of me and @GlynnPhillips getting together and working it out.

I'm going to close this issue. If you'd like to open a separate one to discuss Selenium then that'd be cool. I imagine it won't make it into a 3.x release because there would be breaking changes, but definitely could be a consideration for pa11y 4.0.
