### ISSUE TITLE
Could testing be performed on fragments of HTML?

### ISSUE THREAD

**Issue by benedfit** [nature/pa11y#71]
Not sure of the feasibility of this but it would be great to be able to run pa11y against a fragment of HTML as well testing full pages.

**Comment by rowanmanning** [comment]
Technically yes this *should* be feasible, but there's no way to do this with pa11y right now. One option in the shorter-term is for your back-end to be able to serve up just the bits of HTML that you need because HTML CodeSniffer (the tool we use under the hood) is built to take the whole page into consideration.

Does that answer your question?

**Comment by benedfit** [comment]
Thanks, I'll go with your suggested approach in the short-term

**Comment by rowanmanning** [comment]
Going to say that actually we probably won't support this in pa11y.
